sudo: required
language: ruby
addons:
  apt:
    packages:
      - docker-ce
  ssh_known_hosts: ec2-35-158-221-148.eu-central-1.compute.amazonaws.com
services:
  - docker

script:
  - cd src && docker build -t tugrulelmas/customer-inviter .